### ISSUE TITLE
way to customise the list

### ISSUE THREAD

**Issue by gadour97** [awhite/lastfm-collage-generator#1]
can you add a feature that let us customise the list or at least collect the (albums/artists) at the end of the pic? (black spots in the middle they're really annoying and
I am tired of adding album photos to last.fm to get the perfect picture (14x14) which is awesome by the way. 👍 
(sorry for my english) ^^
![14 14 name](https://user-images.githubusercontent.com/31381068/34969548-8b279fdc-fa6f-11e7-93fd-a5a9e9bf6495.png)

**Comment by awhite** [comment]
There is now a feature to hide missing artwork.
