### ISSUE TITLE
No Artist images are loading

### ISSUE THREAD

**Issue by Machiventa** [awhite/lastfm-collage-generator#2]
Hello, no matter which option I choose no Artist images are loading with either Firefox or Chrome.

**Comment by awhite** [comment]
This is an issue with the Last.fm API. I will close the issue when it is resolved.

**Comment by Machiventa** [comment]
Ah I see, thank you!

**Comment by awhite** [comment]
Last.fm API has removed support for artist images. Will look into using an alternative API for the images themselves, still backed by the artists according to Last.fm
