### ISSUE TITLE
The "new and improved" collage generator is gone.

### ISSUE THREAD

**Issue by RudeySH** [awhite/lastfm-collage-generator#5]
The new one is gone, but this one still works. What's up with that?

**Comment by awhite** [comment]
Whoops. Investigating now

**Comment by awhite** [comment]
Not sure what happened there. It's back up now. I'll investigate to make sure this doesn't happen again

**Comment by RudeySH** [comment]
Did it's GitHub repository move? The README of this repo includes a link to https://github.com/awhite/lastcollage, which doesn't exist.

Lastcollage works great by the way!

**Comment by awhite** [comment]
That repo is still private, I'm making some final touches before I make it public.

Thanks for your support! I really appreciate it 😀
