### ISSUE TITLE
"Internal Server Error" consistently thrown at certain size of album cover collage 

### ISSUE THREAD

**Issue by SharkyBamboozle** [awhite/lastfm-collage-generator#7]
The website keeps throwing ["Internal Server Error"](https://www.reddit.com/r/lastfm/comments/klrv2n/any_suggestions_for_a_working_20x20_album_cover/) for a certain set of settings and a specific profile:

I tried to generate 20x20 album cover collage for "forever" w/o title overlay and with replacement. It works for my profile, but for the profile of my friend, it throws the exception, every time I go over a size of 10x11 or alternatively for 20x20 if the custom timeframe is extended beyond a certain point.

I tried to adjust the size of the grid to figure out at which album the generation fails. I have no further evidence that the album actually triggers the fail, but this is the [album reference](https://www.last.fm/music/Joaqu%C3%ADn+Rodrigo/Julian+Bream+Edition,+Volume+28:+Concierto+de+Aranjuez+%2F+Fantas%C3%ADa+para+un+gentilhombre+%2F+Tres+piezas+espa%C3%B1olas+%2F+Invocation+et+Danse).

The profile triggering the fail contains 66,801 scrobbled and 3,205 albums, so I doubt that data size is the issue. It worked with my profile with the same settings and a larger amount of scrobbles.

**Comment by awhite** [comment]
Just pushed an update that should fix this. Please let me know if the issue still persists.

**Comment by SharkyBamboozle** [comment]
The first time I tried it, the same error was thrown, in all subsequent queries, it worked. For profiles that were affected by this issue only, the resulting collage is missing a square in the right bottom corner now. I suspect from manually excluding the special item that was responsible? What actually caused the exception?
